export const DHAKA_AREAS = [
  "Dhanmondi",
  "Gulshan",
  "Banani",
  "Baridhara",
  "Motijheel",
  "Ramna",
  "Mirpur",
  "Uttara",
  "Mohammadpur",
  "Bashundhara",
  "Rampura",
  "Badda",
  "Khilgaon",
  "Malibagh",
  "Shantinagar",
  "Wari",
  "Old Dhaka",
  "Lalbagh",
  "Chawkbazar",
  "Mohakhali",
  "Tejgaon",
  "Farmgate",
  "Kafrul",
  "Cantonment",
  "Shyamoli",
  "Adabor",
  "Jatrabari",
  "Demra",
  "Savar",
] as const;

export type DhakaArea = (typeof DHAKA_AREAS)[number];